UniversityCourseAndResultManagementApp/Models/Department.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityCourseAndResultManagementApp.Models
{
    public class Department
    {
       public int Id { get; set; }
        [Required(ErrorMessage = "Please Enter Department Code")]
        [StringLength(7, MinimumLength = 2, ErrorMessage = "Length must be 2 to 7 characters")]

        public String Code { get; set; }
        [Required(ErrorMessage = "Please Enter Department Name")]
        public String Name { get; set; }

        public List<Teacher> Teachers { get; set; }
        public List<Course> Courses { get; set; }

    }
}

UniversityCourseAndResultManagementApp/Controllers/CourseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementApp.Manager;
using UniversityCourseAndResultManagementApp.Models;

namespace UniversityCourseAndResultManagementApp.Controllers
{
    public class CourseController : Controller
    {
        DepartmentManager anDepartmentManager = new DepartmentManager();
        CourseManager anCourseManager = new CourseManager();
        //
        // GET: /Course/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaveCourse()
        {
            //ViewBag.departments = anDepartmentManager.GetAllDepartment();
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.semesters = GetSemesterDropDownList();

            // ViewBag.semesters = anCourseManager.GetAllSemester();
            return View();
        }
        [HttpPost]
        public ActionResult SaveCourse(Course course)
        {

            //ViewBag.departments = anDepartmentManager.GetAllDepartment();
            ViewBag.departments = GetDepartmentDropDownList();
            //ViewBag.semesters = anCourseManager.GetAllSemester();
            ViewBag.semesters = GetSemesterDropDownList();
            ViewBag.msg = anCourseManager.Save(course);
            return View();
        }
        private List<SelectListItem> GetDepartmentDropDownList()
        {
            var departments = anDepartmentManager.GetAllDepartment();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Department dept in departments)
            {
                SelectListItem item = new SelectListItem() { Value = dept.Id.ToString(), Text = dept.Name };
                items.Add(item);
            }
            return items;
        }

        private List<SelectListItem> GetSemesterDropDownList()
        {
            var semesters = anCourseManager.GetAllSemester();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Semester semester in semesters)
            {
                SelectListItem item = new SelectListItem() { Value = semester.Id.ToString(), Text = semester.Name };
                items.Add(item);
            }
            return items;
        }

    }
}

UniversityCourseAndResultManagementApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementApp.Manager;
using UniversityCourseAndResultManagementApp.Models;

namespace UniversityCourseAndResultManagementApp.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager anDepartmentManager = new DepartmentManager();
        TeacherManager anTeacherManager = new TeacherManager();
        CourseManager anCourseManager = new CourseManager();
        //
        // GET: /Department/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaveDepartment()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveDepartment(Department department)
        {
            ViewBag.msg = anDepartmentManager.SaveDepartment(department);
            return View();
        }

        public ActionResult ViewDepartment()
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();
            return View();
        }


        public ActionResult SaveTeacher()
        {
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.designations = GetDesignationDropDownList();
            return View();
        }
        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.designations = GetDesignationDropDownList();
            ViewBag.msg = anTeacherManager.SaveTeacher(teacher);
            return View();
        }
        private List<SelectListItem> GetDepartmentDropDownList()
        {
            var departments = anDepartmentManager.GetAllDepartment();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Department dept in departments)
            {
                SelectListItem item = new SelectListItem() { Value = dept.Id.ToString(), Text = dept.Name };
                items.Add(item);
            }
            return items;
        }

        private List<SelectListItem> GetDesignationDropDownList()
        {
            var designations = anDepartmentManager.GetAllDesignation();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Teacher teacher in designations)
            {
                SelectListItem item = new SelectListItem() { Value = teacher.DesignationId.ToString(), Text = teacher.DesignationName };
                items.Add(item);
            }
            return items;
        }


        public ActionResult CourseAssaignTeacher()
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();
            return View();
        }
        [HttpPost]
        public ActionResult CourseAssaignTeacher(Teacher teacher)
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();
            ViewBag.assaigned = anTeacherManager.AssaignCourseTeacher(teacher);
            return View();
        }

        public JsonResult GetTeacherCourseByDepartmentId(int id)
        {
            var teacherInfo = anDepartmentManager.GetTeacherByDepartmentId(id);
            var courseInfo = anDepartmentManager.GetCourseByDepartmentId(id);
            Department department = new Department();
            department.Courses = courseInfo;
            department.Teachers = teacherInfo;
            return Json(department);
        }

        public JsonResult GetTeacherInfoById(int id)
        {
            var teacherInfo = anDepartmentManager.GetTeacherInfoById(id);
            return Json(teacherInfo);
        }
        public JsonResult GetCourseInfoById(int id)
        {
            var courseInfo = anDepartmentManager.GetCourseInfoById(id);
            return Json(courseInfo);
        }

        public ActionResult ViewCourseStatics()
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();

            return View();
        }
        [HttpPost]
        public ActionResult ViewCourseStatics(int id)
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();

            return View();
        }
        public JsonResult GetCoursesByDepartmentId(int id)
        {
            var courses = anCourseManager.GetAllCourses(id);

            foreach (Course course in courses)
            {

                course.TeacherName = anTeacherManager.GetAssaigned(course.Id).ToString();
            }


            return Json(courses);
        }

        public ActionResult UnassignCourses()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult UnassignCourses(Course course)
        {
            ViewBag.Assigned = 
            ViewBag.Message = anDepartmentManager.UnassignCourses();

            return View();
        }
        public JsonResult IsCourseAssigned(int aVal)
         {


             var returnObj = anDepartmentManager.IsCourseAssigned(aVal);
        

            return Json(returnObj);
          }
    }
}

UniversityCourseAndResultManagementApp/Views/Department/CourseAssaignTeacher.cshtml
@using UniversityCourseAndResultManagementApp.Models
@{
    ViewBag.Title = "Course Assaign Teacher";
}
<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Save</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <style>
        label.error {
            color: red;
            font-style: italic;
        }
    </style>
</head>
<body>
    <h3>Courses</h3>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Save Course", "SaveCourse", "Course")</li>
        <li>@Html.ActionLink("Course Statics", "ViewCourseStatics", "Department")</li>
        <li>@Html.ActionLink("Course Assign Teacher", "CourseAssaignTeacher", "Department")</li>
        <li>@Html.ActionLink("Unassign Courses", "UnassignCourses", "Department")</li>
    </ul>
</div>
<br/>
<br/>
<div class="container">
    <h4>Course Assaign To Teacher</h4>
    <hr/>
        <form class="form-horizontal" method="POST" id="CourseAssaign">
            <div class="form-group">
                <label class="col-sm-2" for="DepartmentId">Department</label>
                <div class="col-sm-6">
                    <select id="DepartmentId" name="DepartmentId" class="form-control" onchange="">
                        <option value="">Select</option>
                        @foreach (Department department in ViewBag.departments)
                        {
                            <option value="@department.Id">@department.Name</option>
                        }
                    </select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2" for="Id">Teacher</label>
                <div class="col-sm-6">
                    <select id="Id" name="Id" class="form-control" onchange=""></select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2" for="CreditTake">Credit to be taken</label>
                <div class="col-sm-6">
                    <input readonly id="CreditTake" class="form-control" name="CreditTake" type="text" value=""/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2" for="CreditLeft">Remaining Credit</label>
                <div class="col-sm-6">
                    <input readonly id="CreditLeft" class="form-control" name="CreditLeft" type="text" value=""/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2" for="CourseId">Course Code</label>
                <div class="col-sm-6">
                    <select id="CourseId" name="CourseId" class="form-control" onchange=""></select>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2" for="Name">Name</label>
                <div class="col-sm-6">
                    <input readonly id="Name" class="form-control" name="Name"/>
                </div>
            </div>
            <div class="form-group">
                <label class="col-sm-2" for="Credit">Credit</label>
                <div class="col-sm-6">
                    <input readonly id="Credit" class="form-control" name="Credit" type="text"/>
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-primary" onclick="myFunction()" value="submit">Save</button>
                </div>
            </div>
        </form>
    @if (ViewBag.assaigned != null)
    {
         if (ViewBag.assaigned == 2)
        {
            <label>Course already assaigned !</label>
        }
        else
        {
            <label>Course assaigned sucessfully !</label>
        }
    }
</div>
@section scripts{
    <script src="~/Scripts/jquery.validate.js"></script>
    <script>
        $(document).ready(function() {
            $("#DepartmentId").change(function() {
                var deptId = $("#DepartmentId").val();
                $("#CourseId").empty();
                $("#Id").empty();
                $("#CourseId").append('<option value="">Select</option>');
                $("#Id").append('<option value="">Select</option>');
                var json = { id: deptId };
                $.ajax({
                    type: "POST",
                    url: '/Department/GetTeacherCourseByDepartmentId',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {
                        $.each(data.Teachers, function(key, value) {
                            $("#Id").append('<option value="' + value.Id + '">' + value.Name + '</option>');
                        });
                        $.each(data.Courses, function(key, value) {
                            $("#CourseId").append('<option value="' + value.Id + '">' + value.Code + '</option>');

                        });
                    }
                });
            });

            $("#Id").change(function() {
                var tId = $("#Id").val();
                $("#CreditTake").empty();
                $("#CreditLeft").empty();
                var json = { id: tId };
                $.ajax({
                    type: "POST",
                    url: '/Department/GetTeacherInfoById',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {

                        $("#CreditTake").val(data.CreditTake);
                        $("#CreditLeft").val(data.CreditLeft);
                    }
                });
            });

            $("#CourseId").change(function() {
                var cId = $("#CourseId").val();
                $("#Name").empty();
                $("#Credit").empty();
                var json = { id: cId };
                $.ajax({
                    type: "POST",
                    url: '/Department/GetCourseInfoById',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function(data) {

                        $("#Name").val(data.Name);
                        $("#Credit").val(data.Credit);
                    }
                });
            });

            $("form").submit(function () {
                var remain = $('#CreditLeft').val();
                var credit = $('#Credit').val();

                if (remain<credit) {
                    return confirm('Course credit is more than Remaining Credit . Do you want to proceed?');
                }
            });


            $("#CourseAssaign").validate({
                rules: {
                    DepartmentId: "required",
                    CourseId: "required",
                    Id: "required"

                },
                messages: {
                    DepartmentId: "Please select department",
                    CourseId: "Please select any Course",
                    Id: "Please select Teacher"
                }
            });
        });
    </script>
}
</body>
</html>

UniversityCourseAndResultManagementApp/Views/Department/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3>Department</h3>

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Save Department", "SaveDepartment", "Department")</li>
        <li>@Html.ActionLink("View Department", "ViewDepartment", "Department")</li>
        <li>@Html.ActionLink("Save Teacher", "SaveTeacher", "Department")</li>
    </ul>
</div>

UniversityCourseAndResultManagementApp/Views/Department/SaveDepartment.cshtml
@model UniversityCourseAndResultManagementApp.Models.Department
@{
    ViewBag.Title = "SaveDepartment";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Save</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <style>
        .field-validation-error {
            color: red;
        }

        .row {
            margin-bottom: 10px
        }
    </style>
</head>

<body>
    <h3>Department</h3>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Save Department", "SaveDepartment", "Department")</li>
            <li>@Html.ActionLink("View Department", "ViewDepartment", "Department")</li>
            <li>@Html.ActionLink("Save Teacher", "SaveTeacher", "Department")</li>
        </ul>
    </div>
    <br />
    <br />
    <div class="container">
        @using (Html.BeginForm(new { @class = "form-horizontal" }))
        {
            <h4>Save Department</h4>
            <hr/>
            <div class="row">
                @Html.LabelFor(m => m.Code, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Code, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Code)
                </div>
            </div>
            <div class="row">
                @Html.LabelFor(m => m.Name, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
            </div>
            <div class="row">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" class="btn btn-primary" value="Save" />
                </div>
            </div>
            <label>@ViewBag.msg</label>
        }
    </div>
    <script src="~/Scripts/jquery-1.10.2.js"></script>

    <script src="~/Scripts/jquery.validate.js"></script>

    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>

</body>
</html>

UniversityCourseAndResultManagementApp/Views/Department/SaveTeacher.cshtml
@model UniversityCourseAndResultManagementApp.Models.Teacher
@{
    ViewBag.Title = "Save Teacher";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Save</title>
    <style>
        .field-validation-error {
            color: red;
        }
        .row {
            margin-bottom: 10px
        }
    </style>
</head>
<body>
    <h3>Department</h3>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Save Department", "SaveDepartment", "Department")</li>
            <li>@Html.ActionLink("View Department", "ViewDepartment", "Department")</li>
            <li>@Html.ActionLink("Save Teacher", "SaveTeacher", "Department")</li>
        </ul>
    </div>
    <br/>
    <br/>
    <div class="container">
        @using (Html.BeginForm())
        {
            <h4>Save Teacher</h4>
            <hr />
                <div class="row">
                    @Html.LabelFor(m => m.Name, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Name)
                    </div>
                </div>
                <div class="row">
                    @Html.LabelFor(m => m.Address, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Address, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Address)
                    </div>
                </div>
                <div class="row">
                    @Html.LabelFor(m => m.Email, new { @class = "control-label col-md-2"})
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.Email)
                    </div>
                </div>
                <div class="row">
                    @Html.LabelFor(m => m.ContactNo, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.ContactNo, new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.ContactNo)
                    </div>
                </div>
                <div class="row">
                    @Html.LabelFor(m => m.DesignationId, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.DesignationId, new SelectList(ViewBag.designations, "Value", "Text"), new { @class = "form-control" })
                        @Html.ValidationMessageFor(m => m.DesignationId)
                    </div>
                </div>
                <div class="row">
                    @Html.LabelFor(m => m.DepartmentId, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.DropDownListFor(m => m.DepartmentId, new SelectList(ViewBag.departments, "Value", "Text"), new{@class= "form-control" })
                        @Html.ValidationMessageFor(m => m.DepartmentId)
                    </div>
                </div>
                <div class="row">
                    @Html.LabelFor(m => m.CreditTake, new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.TextBoxFor(m => m.CreditTake, new{@class= "form-control" })
                        @Html.ValidationMessageFor(m => m.CreditTake)
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" class="btn btn-primary" value="Save" />
                    </div>
                </div>
                <label>@ViewBag.msg</label>
        }
    </div>

    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
</body>
</html>

UniversityCourseAndResultManagementApp/Views/Department/UnassignCourses.cshtml
@{
    ViewBag.Title = "UnassignCourses";
}
<h3>Courses</h3>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Save Course", "SaveCourse", "Course")</li>
        <li>@Html.ActionLink("Course Statics", "ViewCourseStatics", "Department")</li>
        <li>@Html.ActionLink("Course Assign Teacher", "CourseAssaignTeacher", "Department")</li>
        <li>@Html.ActionLink("Unassign Courses", "UnassignCourses", "Department")</li>
    </ul>
</div>
<br />
<br />
@using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", id = "UnassignCourses" }))
{
    <h4>Unassign Courses</h4>
    <hr/>
    <div class="form-group">
        <div class="col-md-4">
            <button id="unassignCourese" onclick="return confirm('You are unassigning all courses,Are you sure?');" name="unassignCourese" class="btn btn-primary">Unassign Courses</button>
        </div>
    </div>
}
<div class="form-group">
    <label class="col-md-4 control-label"></label>
    <div class="col-md-4 ">
        @if (ViewBag.Message != null)
        {
            <label class="label-success">@ViewBag.Message</label>
        }
    </div>
</div>

UniversityCourseAndResultManagementApp/Views/Department/ViewCourseStatics.cshtml
@{
    ViewBag.Title = "ViewCourseStatics";
}

    <h3>Courses</h3>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li>@Html.ActionLink("Save Course", "SaveCourse", "Course")</li>
            <li>@Html.ActionLink("Course Statics", "ViewCourseStatics", "Department")</li>
            <li>@Html.ActionLink("Course Assign Teacher", "CourseAssaignTeacher", "Department")</li>
            <li>@Html.ActionLink("Unassign Courses", "UnassignCourses", "Department")</li>
        </ul>
    </div>
    <br/>
<br/>
<div class="container">
    @using (Html.BeginForm(null, null, FormMethod.Post, new { @class = "form-horizontal", id = "viewCourseStatics" }))
    {
        <h4>View Course Statics</h4>
        <hr />
        <div class="form-group">
            <label class="col-md-2" for="departmentId">Select Department</label>
            <div class="col-md-4">
                <select class="form-control" name="departmentId" id="departmentId">
                    <option value="">--Select--</option>
                    @foreach (var department in ViewBag.Departments)
                    {
                        <option value="@department.Id">@department.Name</option>
                    }
                </select>
            </div>
        </div>
    }
    <table id="myTable" class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name/Title</th>
                <th>Semester</th>
                <th>Assaigned To</th>
            </tr>
        </thead>
        <tbody id="tableBody"></tbody>
    </table>
</div>
@section scripts
{
    <script>
        $(document).ready(function () {
            $("#myTable").hide();
            $("#departmentId").change(function () {
                var deptId = $("#departmentId").val();
                $("#myTable").show();
                $("#tableBody").empty();
                var json = { id: deptId };
                $.ajax({
                    type: "POST",
                    url: '/Department/GetCoursesByDepartmentId',
                    contentType: "application/json; charset=utf-8",
                    data: JSON.stringify(json),
                    success: function (data) {

                        $.each(data, function (key, value) {


                            $("#tableBody").append('<tr><td>' + value.Code + '</td><td>' + value.Name + '</td><td>' + value.SemName + '</td><td>' + value.TeacherName + '</td></tr>');

                        });
                    }
                });
            });
        });
    </script>
}

UniversityCourseAndResultManagementApp/Views/Department/ViewDepartment.cshtml
@using UniversityCourseAndResultManagementApp.Models

@{
    ViewBag.Title = "ViewDepartment";
    List<Department> departments = ViewBag.departments;
}
<h3>Department</h3>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Save Department", "SaveDepartment", "Department")</li>
        <li>@Html.ActionLink("View Department", "ViewDepartment", "Department")</li>
        <li>@Html.ActionLink("Save Teacher", "SaveTeacher", "Department")</li>
    </ul>
</div>
<br />
<br />
<div class="container">
    <h4>View All Departments</h4>
    <hr />
    <table id="myTable" class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Code</th>
                <th>Name</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Department department in departments)
            {
                <tr>
                    <td>@department.Code</td>
                    <td>@department.Name</td>
                </tr>
            }
        </tbody>
    </table>
</div>