UniversityCourseAndResultManagementApp/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace UniversityCourseAndResultManagementApp.Models
{
    public class Student
    {
       
        public int Id { get; set; }
        [Required(ErrorMessage = "Please enter student name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter student email")]
        [RegularExpression(@"[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?", ErrorMessage = "Please enter valid email")]
        
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter student contact no.")]
        [StringLength(14,MinimumLength = 11,ErrorMessage = "Contact no must be between 11 to 14 digit")]
        [RegularExpression(@"^\d+$", ErrorMessage = "Contact no must be numeric")]
        [DisplayName("Contact No")]

        public string ContactNo { get; set; }
        public string Date { get; set; }
        [Required(ErrorMessage = "Please enter student address")]
        public string Address { get; set; }
        
        public string Department { get; set; }
        [Required(ErrorMessage = "Please select a department")]
        [DisplayName("Department")]
        public int DepartmentId { get; set; }
        [DisplayName("Reg No")]

        public string RegNo { get; set; }
        public string Year { get; set; }
        public string Grade { get; set; }
        public int GradeId { get; set; }
        public string Course { get; set; }
        public int CourseId { get; set; }
        public List<Course> Courses { get; set; }

        public string Code { get; set; }
       
  
    }
}

UniversityCourseAndResultManagementApp/Controllers/DepartmentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementApp.Manager;
using UniversityCourseAndResultManagementApp.Models;

namespace UniversityCourseAndResultManagementApp.Controllers
{
    public class DepartmentController : Controller
    {
        DepartmentManager anDepartmentManager = new DepartmentManager();
        TeacherManager anTeacherManager = new TeacherManager();
        CourseManager anCourseManager = new CourseManager();
        //
        // GET: /Department/
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SaveDepartment()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SaveDepartment(Department department)
        {
            ViewBag.msg = anDepartmentManager.SaveDepartment(department);
            return View();
        }

        public ActionResult ViewDepartment()
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();
            return View();
        }


        public ActionResult SaveTeacher()
        {
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.designations = GetDesignationDropDownList();
            return View();
        }
        [HttpPost]
        public ActionResult SaveTeacher(Teacher teacher)
        {
            ViewBag.departments = GetDepartmentDropDownList();
            ViewBag.designations = GetDesignationDropDownList();
            ViewBag.msg = anTeacherManager.SaveTeacher(teacher);
            return View();
        }
        private List<SelectListItem> GetDepartmentDropDownList()
        {
            var departments = anDepartmentManager.GetAllDepartment();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Department dept in departments)
            {
                SelectListItem item = new SelectListItem() { Value = dept.Id.ToString(), Text = dept.Name };
                items.Add(item);
            }
            return items;
        }

        private List<SelectListItem> GetDesignationDropDownList()
        {
            var designations = anDepartmentManager.GetAllDesignation();
            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value="", Text="---Select---"}
            };
            foreach (Teacher teacher in designations)
            {
                SelectListItem item = new SelectListItem() { Value = teacher.DesignationId.ToString(), Text = teacher.DesignationName };
                items.Add(item);
            }
            return items;
        }


        public ActionResult CourseAssaignTeacher()
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();
            return View();
        }
        [HttpPost]
        public ActionResult CourseAssaignTeacher(Teacher teacher)
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();
            ViewBag.assaigned = anTeacherManager.AssaignCourseTeacher(teacher);
            return View();
        }

        public JsonResult GetTeacherCourseByDepartmentId(int id)
        {
            var teacherInfo = anDepartmentManager.GetTeacherByDepartmentId(id);
            var courseInfo = anDepartmentManager.GetCourseByDepartmentId(id);
            Department department = new Department();
            department.Courses = courseInfo;
            department.Teachers = teacherInfo;
            return Json(department);
        }

        public JsonResult GetTeacherInfoById(int id)
        {
            var teacherInfo = anDepartmentManager.GetTeacherInfoById(id);
            return Json(teacherInfo);
        }
        public JsonResult GetCourseInfoById(int id)
        {
            var courseInfo = anDepartmentManager.GetCourseInfoById(id);
            return Json(courseInfo);
        }

        public ActionResult ViewCourseStatics()
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();

            return View();
        }
        [HttpPost]
        public ActionResult ViewCourseStatics(int id)
        {
            ViewBag.departments = anDepartmentManager.GetAllDepartment();

            return View();
        }
        public JsonResult GetCoursesByDepartmentId(int id)
        {
            var courses = anCourseManager.GetAllCourses(id);

            foreach (Course course in courses)
            {

                course.TeacherName = anTeacherManager.GetAssaigned(course.Id).ToString();
            }


            return Json(courses);
        }

        public ActionResult UnassignCourses()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult UnassignCourses(Course course)
        {
            ViewBag.Assigned = 
            ViewBag.Message = anDepartmentManager.UnassignCourses();

            return View();
        }
        public JsonResult IsCourseAssigned(int aVal)
         {


             var returnObj = anDepartmentManager.IsCourseAssigned(aVal);
        

            return Json(returnObj);
          }
    }
}

UniversityCourseAndResultManagementApp/Controllers/EnrollController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UniversityCourseAndResultManagementApp.Manager;
using UniversityCourseAndResultManagementApp.Models;

namespace UniversityCourseAndResultManagementApp.Controllers
{
    public class EnrollController : Controller
    {
        EnrollManager anStudentManger = new EnrollManager();
        //
        // GET: /Enroll/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Save()
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            return View();
        }
        [HttpPost]
        public ActionResult Save(Student student)
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            ViewBag.msg = anStudentManger.Save(student);
            return View();
        }
        public JsonResult GetStudentInfo(Student student)
        {
            var studentInfo = anStudentManger.GetStudentDetailsWithRegNo(student);
            var courses = anStudentManger.GetAllCourses(studentInfo.DepartmentId);
            studentInfo.Courses = courses;
            return Json(studentInfo);
        }

        public ActionResult SaveResult()
        {
            ViewBag.students = anStudentManger.GetAllStudentRegNo();

            return View();
        }
        [HttpPost]
        public ActionResult SaveResult(Student student)
        {

            ViewBag.students = anStudentManger.GetAllStudentRegNo();
            ViewBag.msg = anStudentManger.SaveResult(student);

            return View();
        }

        public JsonResult GetStudentInformation(Student student)
        {
            var studentInfo = anStudentManger.GetStudentDetailsWithRegNo(student);
            var courses = anStudentManger.GetAllEnrollCourses(student.Id);
            studentInfo.Courses = courses;
            return Json(studentInfo);
        }
    }
}

UniversityCourseAndResultManagementApp/Controllers/StudentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using Rotativa;
using UniversityCourseAndResultManagementApp.Manager;
using UniversityCourseAndResultManagementApp.Models;

namespace UniversityCourseAndResultManagementApp.Controllers
{
    public class StudentController : Controller
    {
        StudentManager aStudentManager = new StudentManager();
        public ActionResult Index()
        {

            return View();
        }

        public ActionResult Save()
        {

            ViewBag.Departments = GetDepartmentForDropDownList();
            return View();
        }

        [HttpPost]
        public ActionResult Save(Student student)
        {
            ViewBag.Departments = GetDepartmentForDropDownList();

            DateTime myDateTime = new DateTime();
            myDateTime = DateTime.ParseExact(student.Date, "dd-MM-yyyy", null);
            String date = myDateTime.ToString("yyyy-MM-dd");
            student.Date = date;
            //student.Department = aStudentManager.GetDepartment(student);

            String year = myDateTime.Year.ToString();           
            //student.RegNo = student.Department + "-" + year + "-";
            student.RegNo = year;

            
            ViewBag.Message = aStudentManager.Save(student);
            
            string email = student.Email;
            TempData["email"] = email;
            if (ViewBag.Message == "1")
            {
                //ShowStudentInfo(student);
                return RedirectToAction("ShowStudentInfo","Student");
            }

            return View();

        }
        private List<SelectListItem> GetDepartmentForDropDownList()
        {
            var departments = aStudentManager.GetAllDepartments();

            List<SelectListItem> items = new List<SelectListItem>()
            {
                new SelectListItem(){Value = "", Text = "--Select--"}
            };

            foreach (Department dept in departments)
            {
                SelectListItem item = new SelectListItem() { Value = dept.Id.ToString(), Text = dept.Code };
                items.Add(item);
            }

            return items;
        }
        [HttpGet]
        public ActionResult ShowStudentInfo(Student aStudent)
        {
            

            Student student = new Student();
            student.Email = TempData["email"].ToString();
            //string email = aStudent.Email;

           Student student1 = aStudentManager.GetStudent(student);
           ViewBag.Student = student1;
            return View();
        }

        public ActionResult ViewStudentResult()
        {
            ViewBag.RegNos = aStudentManager.GetAllRegNos();
            return View();
        }
        [HttpPost]
        public ActionResult ViewStudentResult(Student student)
        {
            ViewBag.RegNos = aStudentManager.GetAllRegNos();
            
            student.Id = (int)TempData["Id"];
            
            
            return RedirectToAction("GeneratePdf", "Student");
            return View();
        }
        public JsonResult GetStudentInfoById(int studentId)
        {
            Student aStudent = aStudentManager.GetStudentInfo(studentId);
            TempData["Id"] = studentId;
            
            return Json(aStudent);
        }
        public JsonResult GetStudentResultByStudentId(int studentId)
        {
            
            List<StudentResultVM> studentResults = aStudentManager.GetAllCourseResult(studentId);

            return Json(studentResults);
        }

        //public ActionResult ShowResult(Student student)
        //{
            
        //    return View();
        //}



        public ActionResult GeneratePdf(Student student)
        {

            student.Id = (int)TempData["Id"];
            ViewBag.Student = aStudentManager.GetStudentInfoForPdf(student);

            List<StudentResultVM> studentResults = aStudentManager.GetAllCourseResult(student.Id);
            ViewBag.Result = studentResults;
            return new ViewAsPdf("GeneratePdf", "Student")
            {
                FileName = "Result sheet.pdf"
            };
        }
        
	}
}

UniversityCourseAndResultManagementApp/Views/Student/GeneratePdf.cshtml
@using UniversityCourseAndResultManagementApp.Models



@{
    Layout = null;
    ViewBag.Title = "ShowResult";
    List<StudentResultVM> studentResults = ViewBag.Result;
    Student student = ViewBag.Student;
}


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ViewResult</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" />
</head>
<body>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <img src="~/images/IIUC-Logo.gif" style="width:480px;height:39px;">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    
<h4>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<u>Result sheet</u></h4>
    
     <h5 style="float: right" id="date"></h5>

<div>

    <table>
        <tr>
            <td><label class="col-md-4 control-label" for="Name">Name</label></td>
            <td><label class="col-md-4 control-label" for="Name">@student.Name</label></td>
        </tr>
        <tr>
            <td><label class="col-md-4 control-label" for="Email">Email</label></td>
            <td><label class="col-md-4 control-label" for="Email">@student.Email</label></td>
        </tr>
        <tr>
            <td><label class="col-md-4 control-label" for="Email">Reg No.</label></td>
            <td><label class="col-md-4 control-label" for="Email">@student.RegNo</label></td>
        </tr>
    </table>
    <br>
    <br>
    <p>Course wise grades:</p>
    <table id="myTable" class="table table-bordered table-hover table-striped">
        <thead>
        <tr>
            <th>Course Code</th>
            <th>Course Name</th>
            <th>Grade</th>
        </tr>

        </thead>
        <tbody id="tableBody">
        @foreach (StudentResultVM studentResult in studentResults)
        {
            <tr>
                <td>@studentResult.CourseCode</td>
                <td>@studentResult.CourseName</td>
                <td>@studentResult.Grade</td>
            </tr>

        }
        </tbody>
    </table>
</div>
    <script>
        n = new Date();
        y = n.getFullYear();
        m = n.getMonth() + 1;
        d = n.getDate();
        document.getElementById("date").innerHTML = "Date: "+ m + "/" + d + "/" + y;
    </script>
</body>
</html>

UniversityCourseAndResultManagementApp/Views/Student/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h3>Student</h3>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("Register", "Save", "Student")</li>
        <li>@Html.ActionLink("Save Result", "SaveResult", "Enroll")</li>
        <li>@Html.ActionLink("View Result", "ViewStudentResult", "Student")</li>
        <li>@Html.ActionLink("Enroll", "Save", "Enroll")</li>
    </ul>

</div>

UniversityCourseAndResultManagementApp/Views/Student/Save.cshtml
@model UniversityCourseAndResultManagementApp.Models.Student


@{
    ViewBag.Title = "Register";
    
}

@section style
{
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<link href="~/Content/datepicker.css" rel="stylesheet" />
<link href="~/Content/jquery-ui.css" rel="stylesheet" />
<link href="~/Content/Site.css" rel="stylesheet" />

<style>
    .field-validation-error {
        font-style: italic;
        color: red;
    }
</style>


    
}
   

    <h3>Student</h3>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">


        <li>@Html.ActionLink("Register", "Save", "Student")</li>
        <li>@Html.ActionLink("Save Result", "SaveResult", "Enroll")</li>
        <li>@Html.ActionLink("View Result", "ViewStudentResult", "Student")</li>
        <li>@Html.ActionLink("Enroll", "Save", "Enroll")</li>
    </ul>

</div>
<h4>Register</h4>

<br/>
    @using (Html.BeginForm(null,null,FormMethod.Post,new { @class = "form-horizontal", id = "saveStudentForm" }))
    {
        
            <div class="form-group">
                @Html.LabelFor(m => m.Name, new {@class = "col-md-4 control-label"})
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.Name, new {@class = "form-control input-md"})
                    @Html.ValidationMessageFor(m => m.Name)
                </div>
                
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Email, new {@class = "col-md-4 control-label"})
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.Email, new {@class = "form-control input-md"})
                    @Html.ValidationMessageFor(m => m.Email)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.ContactNo, new {@class = "col-md-4 control-label"})
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.ContactNo, new {@class = "form-control input-md"})
                    @Html.ValidationMessageFor(m => m.ContactNo)
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="Date">Date</label>
                <div class="col-md-4">
                    <input id="Date" name="Date" type="text" placeholder="dd-mm-yyyy" class="form-control input-md">

                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.DepartmentId, new {@class = "col-md-4 control-label"})
                <div class="col-md-4">
                    @Html.DropDownListFor(x => x.DepartmentId, new SelectList(ViewBag.Departments, "Value", "Text"),new {@class = "form-control input-md"})
                    @Html.ValidationMessageFor(m => m.DepartmentId)
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(m => m.Address, new {@class = "col-md-4 control-label"})
                <div class="col-md-4">
                    @Html.TextBoxFor(m => m.Address, new {@class = "form-control input-md"})
                    @Html.ValidationMessageFor(m => m.Address)
                </div>
            </div>
            <div class="form-group">
                <label class="col-md-4 control-label" for="Register"></label>
                <div class="col-md-4">
                    <button id="Register" name="Register" class="btn btn-primary">Register</button>
</div>
            </div>
       
    }
    <div class="form-group">
        <label class="col-md-4 control-label" ></label>
        <div class="col-md-4 ">
            @if (ViewBag.Message != null)
            {
                <label class="label-success">@ViewBag.Message</label>
            }
        </div>
    </div>

    

    @section Scripts {
        
    <script src="~/Scripts/jquery-1.10.2.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>
    <script src="~/Scripts/jquery-ui-1.12.1.js"></script>
    <script>
        $(document).ready(function () {

            $("#Date").datepicker({
                dateFormat: 'dd-mm-yy',
                changeMonth: true,
                yearRange: '1990:2030',
                changeYear: true,
                gotoCurrent: true

            }).datepicker('setDate', "0");



        });

    </script>

    }
    

UniversityCourseAndResultManagementApp/Views/Student/ShowStudentInfo.cshtml
@using UniversityCourseAndResultManagementApp.Models

@{
    
    Student student = ViewBag.Student;
    
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>ShowStudentInfo</title>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/jquery-1.10.2.js"></script>

</head>
<body>
    <dl class="dl-horizontal">
        <dt>
            <label class="col-md-4 control-label" for="Name">Name</label>
        </dt>

        <dd>
            <label class="col-md-4 control-label" for="Name">@student.Name</label>
        </dd>
        <dt>
            <label class="col-md-4 control-label" for="Email">Email</label>
            
        </dt>

        <dd>
            <label class="col-md-4 control-label" for="Email">@student.Email</label>
        </dd>
        <dt>
            <label class="col-md-4 control-label" for="ContactNo">Contact No.</label>
        </dt>

        <dd>
            <label class="col-md-4 control-label" for="ContactNo">@student.ContactNo</label>
        </dd>
        <dt>
            <label class="col-md-4 control-label" for="Department">Department</label>
        </dt>

        <dd>
            <label class="col-md-4 control-label" for="Department">@student.Department</label>
        </dd>
        <dt>
            <label class="col-md-4 control-label" for="RegNo">Reg No.</label>
        </dt>

        <dd>
            <label class="col-md-4 control-label" for="RegNo">@student.RegNo</label>
        </dd>
        <dt>
            <label class="col-md-4 control-label" for="Address">Address</label>
        </dt>

        <dd>
            <label class="col-md-4 control-label" for="Address">@student.Address</label>
        </dd>
    </dl>



</body>
</html>

UniversityCourseAndResultManagementApp/Views/Student/ViewStudentResult.cshtml
@using UniversityCourseAndResultManagementApp.Models
@model UniversityCourseAndResultManagementApp.Models.Student
@{
    ViewBag.Title = "ViewStudentResult";
    List<Student> studentRegNos = ViewBag.RegNos;
}

<h2>Student</h2>
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">


        <li>@Html.ActionLink("Register", "Save", "Student")</li>
        <li>@Html.ActionLink("Save Result", "SaveResult", "Enroll")</li>
        <li>@Html.ActionLink("View Result", "ViewStudentResult", "Student")</li>
        <li>@Html.ActionLink("Enroll", "Save", "Enroll")</li>
    </ul>

</div>
<h4>View Result</h4>
<br>
<form class="form-horizontal" id="ViewResultForm" method="POST">

    <div class="form-group">
        <label class="col-md-4 control-label" for="studentId">
            Student Reg. No.
        </label>

        <div class="col-md-4">
            <select class="form-control" name="studentId" id="studentId">
                <option value="">--Select--</option>
                @foreach (var student in studentRegNos)
                {
                    <option value="@student.Id">@student.RegNo</option>
                }
            </select>

        </div>

    </div>
    <div class="form-group">
        <label class="col-md-4 control-label" for="Name">Name</label>

        <div class="col-md-4">

            <input readonly type="text" class="form-control" id="Name">
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label" for="Email">Email</label>

        <div class="col-md-4">

            <input readonly type="text" class="form-control" id="Email">
        </div>
    </div>
    <div class="form-group">
        <label class="col-md-4 control-label" for="Department">Department</label>

        <div class="col-md-4">

            <input readonly type="text" class="form-control" id="Department">
        </div>
    </div>

    <div class="form-group">
        <label class="col-md-4 control-label" for="MakePdf"></label>
        <div class="col-md-4">
            @*<a href="@Url.Action("GeneratePdf", "Student")">*@<button type="submit" id="MakePdf" name="MakePdf" class="btn btn-primary">Make PDF</button>@*</a>*@
        </div>
    </div>
    </form>
<div class="form-group">
    <label class="col-md-4 control-label"></label>
    <div class="col-md-4 ">
        @if (ViewBag.Message != null)
        {
            <label class="label-success">@ViewBag.Message</label>
        }
    </div>
</div>



    <table id="resultTable" class="table table-bordered table-hover table-striped">
        <thead>
            <tr>
                <th>Course Code</th>
                <th>Name</th>
                <th>Grade</th>
            </tr>
        </thead>
        <tbody id="tableBody"></tbody>
    </table>

    @section scripts
{
        <script>
            $(document).ready(function () {
                $("#resultTable").hide();
                $("#studentId").change(function () {
                    var stdId = $("#studentId").val();
                    $("#resultTable").show();
                    $("#tableBody").empty();
                    var json = { studentId: stdId };
                    $.ajax({
                        type: "POST",
                        url: '/Student/GetStudentInfoById',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            $("#Name").val(data.Name);
                            $("#Email").val(data.Email);
                            $("#Department").val(data.Department);
                        }
                    });
                    $.ajax({
                        type: "POST",
                        url: '/Student/GetStudentResultByStudentId',
                        contentType: "application/json; charset=utf-8",
                        data: JSON.stringify(json),
                        success: function (data) {

                            $.each(data, function (key, value) {


                                $("#tableBody").append('<tr><td>' + value.CourseCode + '</td><td>' + value.CourseName + '</td><td>' + value.Grade + '</td></tr>');

                            });
                        }
                    });
                });
            });
        </script>
    }